name: revisionv2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 1.2.2
  mongo_dart: 0.10.3
  cupertino_icons: 1.0.6
  intl: 0.19.0
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: 4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
